# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
